import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Link from 'next/link';
import Head from 'next/head';

const Start: NextPage = () => {
  const router = useRouter();
  const { memberId } = router.query;

  return (
    <>
      <Head>
        <title>My neck of the woods</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Start</h1>

      <ul>
        <li>
          <Link href="/register">
            <a>Register</a>
          </Link>
        </li>
        <li>
          <Link href="/login">
            <a>Login</a>
          </Link>
        </li>
      </ul>
    </>
  );
};

export default Start;
